### ISSUE TITLE
Team B2 - Sprint 2 - Ütközési fizika implementálása

### ISSUE THREAD

**Issue by BozsikZsolt** [SzFMV2020-Osz/AutomatedCar-B#125]
Az objektumok mozgásállapota az energiamegmaradás törvényeinek megfelelően változik (gyorsul, lassul, irányt vált, megáll)

- [ ] Ha a vezérelt autó nekimegy egy NPC autónak akkor ez legyen rá hatással (lassuljon le)

- [ ] Ha a vezérelt autó nagyobb sebességgel nekimegy egy „stabil” tereptárgynak (pl. fa), akkor álljon meg, érjen véget a játék, tekintsük úgy, hogy totálkáros.

- [ ] egy táblán azonban át tud menni (el tudja sodorni), csak lassuljon le és sérüljön egy kicsit

**Comment by pintergreg** [comment]
Tudom, hogy nem voltak még kitöltve a a user story issue-k, de ezzel nektek nem kell foglalkozni, így lezárom.
