### ISSUE TITLE
Játék vége kondíció

### ISSUE THREAD

**Issue by aaronrancsik** [SzFMV2020-Osz/AutomatedCar-B#132]
A játék véget ér ha 
- [x] autó hp eléri a nullát
- [x] autó elüt egy gyalogost 
- [x] HP display fix

**Comment by tffbs** [comment]
Minden tickben megvizsgáljuk, hogy 0-e a HP, vagy inkább eseményt váltson ki?

**Comment by pintergreg** [comment]
Az esemény minden bizonnyal erőforráskímélőbb.
