### ISSUE TITLE
Autó hp létrehozása & visszaállítás

### ISSUE THREAD

**Issue by aaronrancsik** [SzFMV2020-Osz/AutomatedCar-B#133]
Gombnyomásra HP visszaállítása.
- [x] Felvenni egy reactive propertyt az AutomatedCar-nak HealthPoints néven
- [x] Dashboardra kivezetni egy gombot, melynek hatására a HP visszaáll

**Comment by lindnermarci** [comment]
B5_car_hp_#131#133 ágon
