### ISSUE TITLE
World Class Modelling

### ISSUE THREAD

**Issue by aaronrancsik** [SzFMV2020-Osz/AutomatedCar-B#14]
Világ class UML: https://drive.google.com/file/d/1Z2PiMbJ_dstfsg5ElBxTfde9KUzypjxt/view?usp=sharing
Világ Init, API Flowchart UML: https://drive.google.com/file/d/1mbHaztZF1_C7KQz12hlNaQPWt8sy3Pir/view?usp=sharing

Update 1: A diagramok az első hétre bemutatható állapotban vannak, nyilván nincs semmi kőbe vésve, de mi ezt így késznek gondoljuk a részünkről. @SzFMV2020-Osz/team-b4 től @kingpeti -vel egyeztettünk, így elvileg a Vizualizációs csapat első körös igényeinek is megfelelnek itt a dolgok. 
Bárki bármi észrevétele van szóljon, és nyugodtan nyissa újra ezt az issue-t ha szerinte ez így nem jó.

**Comment by pintergreg** [comment]
Néhány észrevétel:

- Gondolom, hogy a *Word*, *Professor* és *Address* osztályok valami sablonból maradtak meg.
- Mit csinál a readAllFiles() a World osztályon belül?
    - nem azt mondom, hogy hiba, csak nem értem teljesen a koncepciót
- A dinamikus objektumok kezelését értem, de a statikus objektumok mintha hiányoznának. Vagy ott mindenki simán csak World Object?

**Comment by aaronrancsik** [comment]
> * Gondolom, hogy a _Word_, _Professor_ és _Address_ osztályok valami sablonból maradtak meg.
Igen, még folyamatban van a tervezés, ma/holnap elvileg kész lesz akkor már nem lesz benne semmi ilyesmi.
> * Mit csinál a readAllFiles() a World osztályon belül?
A  readAllFiles() -t a singleton/IoC hívja erre készítünk majd ma szekvencia diagramot, ez illetve esetleges segéd függvények segítségével lesz a teljes inicializáció megvalósítva.
> * A dinamikus objektumok kezelését értem, de a statikus objektumok mintha hiányoznának. Vagy ott mindenki simán csak World Object?
Milyen plusz property-t tulajdonságot kéne adnunk nekik? még gondolkodunk majd rajta.

**Comment by pintergreg** [comment]
> Milyen plusz property-t tulajdonságot kéne adnunk nekik? még gondolkodunk majd rajta.

Pl. út és fa viszonyában: melyiknek lehet nekimenni.

**Comment by aaronrancsik** [comment]
Új frissítések a flowchart diagramban

**Comment by pintergreg** [comment]
Folyamatábra jobb oldali rész: Az egocar példányosításának miért „feltétele” az NPC útvonalak megléte? NPC útvonalakat csak a 2. sprintben, a B3 fog kezelni, de az egocarnak már most létre kell jönnie.

**Comment by aaronrancsik** [comment]
> Folyamatábra jobb oldali rész: Az egocar példányosításának miért „feltétele” az NPC útvonalak megléte? NPC útvonalakat csak a 2. sprintben, a B3 fog kezelni, de az egocarnak már most létre kell jönnie.

Az nem feltétel, azok lépések sorban, de akkor azt kivesszük, de ebben a metódusban van a helye szerintünk. illetve a mi (B2) feladata lesz az NPC a 2. sprintben a github user story-k alapján. Ez egy kicsit ellent mond a jegyzettel.

**Comment by pintergreg** [comment]
> Az nem feltétel, azok lépések sorban, de akkor azt kivesszük, de ebben a metódusban van a helye szerintünk. illetve a mi (B2) feladata lesz az NPC a 2. sprintben a github user story-k alapján. Ez egy kicsit ellent mond a jegyzettel.

Igen, ezt elrontottam. A 2. és 3. sprintben felcseréltem a 2-as és 3-as csapatok user story-ját.

**Comment by aaronrancsik** [comment]
Update: Komponensek/Modulok/Csapatok közötti kommunikáció hierarchia most már része a class diagramnak.

**Comment by tffbs** [comment]
Új verzió: https://app.diagrams.net/#G10Q1DCcb6A96N2n4vte6kETOkbREVdIOa

**Comment by aaronrancsik** [comment]
Régi B2-ben volt érvényes már nem releváns.
