### ISSUE TITLE
Hajtáslánc: Acceptance test 2020-10-21

### ISSUE THREAD

**Issue by pintergreg** [SzFMV2020-Osz/AutomatedCar-B#143]
@SzFMV2020-Osz/team-3 

TL;DR: az autó vezethetetlen, az elvárásokból szinte semmit nem teljesít.

# Gear=P

- elvárt viselkedés: az autó egy helyben marad. A VFB-t akár le is lehetne állítani (Stop metódus, mintha elvesszük a gyújtást, de ez asszem nem volt feladat és lehet, hogy nem várt következményekkel járna).
- ehhez képest:
    - Gázadás esetében az Y érték időnként csökken 10-el, majd visszaáll 0-ra.
    - fék: az Y érték időnként megnő 10-re, majd visszaáll 0-ra.
    - kormány jobbra fordítása: az X érték időnként megnő 10-re, majd visszaáll 0-ra.
    - kormány balra fordítása: az X érték időnként lecsökken 10-re, majd visszaáll 0-ra.
    - mintha egy-két modul azon versenyezve, hogy kié a vezérlés

# Gear=N

- ugyanaz mint a P, de a VFB-t határozottan nem kell leállítani.

# Gear = D

- elvárás, hogy előremenetben lehessen haladni, gázzal gyorsítani, fékkel lassítani, kormánnyal irányt változtatni.
- ehhez képest: 
    - gázadásra az Y érték csökken, ez kb. mintha működne ahogy kell, de a kamera nem követi (ez nem biztos, hogy a modul hibája, de mivel a primitív mozgatás esetében jó volt, lehet, hogy nem úgy van az elmozdulás visszaírva, ahogy a megjelenítés várja)
    - lendület megmaradás is van, de az X érték változása alapján talán picit sok is.
    - gáz és kanyarodás esetében az autó egy helyben forogni kezd irdatlan sebességgel.
    - ha gázt nem adok, csak elfordítom a kormányt akkor semmi nem történik

# Gear = R

- elvárás, hogy hátramenetben lehessen haladni, gázzal gyorsítani, fékkel lassítani, kormánnyal irányt változtatni.
- ehhez képest az autó előre fele mozog (Y csökken), majd ahogy a gázpedál állása visszatér nullára kicsit visszafele is (Y nő). Amikor a gázpedál nulla állásban ez a jelenség megáll.
    - gáz és kanyarodás esetében az autó egy helyben forogni kezd irdatlan sebességgel.
    - ha gázt nem adok, csak elfordítom a kormányt akkor semmi nem történik

**Comment by csonkabalint** [comment]
A Game osztályban még benne van a dummy handling, ha ezt kiszedem, a problémák egy része elműlik, kivéve az, hogy helyben állás utáni megpörök a kocsi. Kivegyem most a dummy handling-et egy külön fix branchben, és utána javítsuk a kormányzást? Vagy inkább egyben az egészet?

**Comment by pintergreg** [comment]
Ha elér érett ahhoz, hogy bejárható legyen a pálya, csak éppen a vezethetőség itt-ott hibás (pl. nem jó a hátramenet, hülyén pörög, vagy úgy gyorsul mintha be lenne húzva a kézifék), akkor a dummy-vezérlést kell kivenni.

Ha nem elég érett a funkció ahhoz, hogy bejárható legyen az autóval a világ (debuggolni lehessen pl. a pályarajzolást), akkor a hajtásláncot kellene inaktiválni (kapcsolhatóvá tenni, hogy egyik vagy másik működjön), mert a jelenlegi helyzet másoknak is problémát okoz(hat).

**Comment by csonkabalint** [comment]
Be lehet járni a pályát.

**Comment by aaronrancsik** [comment]
A dummy vezérlés nélkül tök jól működik :D approved

**Comment by aaronrancsik** [comment]
@SzFMV2020-Osz/team-b3 Valószínűleg tudtok róla, de egy javaslatom lenne, én a kanyarodás szögének mértékét a sebességtől függővé tenném, hogy ne lehessen minimális sebességgel pörögni, de amúgy tényleg nagyon király lett!

**Comment by pintergreg** [comment]
> @SzFMV2020-Osz/team-b3 Valószínűleg tudtok róla, de egy javaslatom lenne, én a kanyarodás szögének mértékét a sebességtől függővé tenném, hogy ne lehessen minimális sebességgel pörögni, de amúgy tényleg nagyon király lett!

Ezt nagyon megfogadnám.

És osztom a véleményt, tényleg jól használható. #144 -val viszont szinte megvan a #3 

A minimál sebességet pörgést meg kéne szüntetni.

**Comment by csonkabalint** [comment]
Annyi próbálkozás volt eddig, hogy az elfordulást, egy (sebesség /
konstans) értékkel szoroztam, de a konstans értékétől függően, vagy nagyon
lomhán kanyarodott kis sebességnél, vagy nem csillapította eléggé a
forgást. Lehet az lenne jó, ha sebesség tartományokra osztva, külön
függvényekkel számolnánk az elfordulást.

Gergő Pintér <notifications@github.com> ezt írta (időpont: 2020. okt. 21.,
Sze, 22:45):
