### ISSUE TITLE
Melyik csapat készíti az alap AutomatedCar osztályt?

### ISSUE THREAD

**Issue by aaronrancsik** [SzFMV2020-Osz/AutomatedCar-B#15]
Ez a kérdés számomra kicsit homályos. HMI és Hajtáslánc akik a legtöbbet foglalkoznak ezzel ha jól értem.
Egyébként mi mint (Világ) csapat biztosítunk interface-ket amiket meg kellene ennek az osztálynak valósítania.

**Comment by pintergreg** [comment]
@aaronrancsik 

Több csapat is módosítja.

Az egyes komponensek (később szenzor, de pl. hajtáslánc már most az első sprintben) az AutomatedCar osztály elemei lesznek. Ezeket bele kell tenni, tehát az érintett csapatok módosítják az osztályt.

A HMI mint műszerfal csak olvassa, a Dashboard megkapja a vezérelt autó referenciáját és egyes adattagokat megjelenít/kiolvas.
A HMI mint input szintén egy komponens ami a buszra ír. (A kiinduló kódban közvetlenül átírom az X,Y értékét, de több komponens is a buszon keresztül fog inputot várni.)

A világmodell csapat felel viszont az AutomatedCar osztály helyéért a modellhierarchiában. Ezt a kiinduló kód többé-kevésbé el is intézi azáltal, hogy AutomatedCar < Car < WorldObject módon előre megadja. (ez módosítható persze a konkrét modell igényei szerint). A modellező csapaté a feladat, hogy további adattagokkal és metódusokkal bővítse ezt és a modell többi elemét is. Ilyen kéréseket a többi csapat is megfogalmazhat, pl. az autóknak legyen tengelytáv attribútuma (mert a kanyarodásnál számolni akarnak vele).

Szóval bizonyos értelemben a modellé, de ez nem azt jelenti, hogy senki más nem írhatja. Ez általában igaz a félév során, nincsenek kizárólagos birtokosai az osztályoknak.

**Comment by aaronrancsik** [comment]
Akkor ha jól értem a mi (világ) feladatunk egy alap AutomatedCar osztály létrehozása, amit majd folyamatosan bővíthet mindenki, és az egyes modulok mind függjenek ettől ha jól értem ne csináljon pl. a vizualizáció egy saját verziót.

**Comment by pintergreg** [comment]
> Akkor ha jól értem a mi (világ) feladatunk egy alap AutomatedCar osztály létrehozása, amit majd folyamatosan bővíthet mindenki, és az egyes modulok mind függjenek ettől ha jól értem ne csináljon pl. a vizualizáció egy saját verziót.

Igen, saját verziót főleg ne csináljon senki. Ha a vizualizáció (vagy valaki más) nem ér el valamit az autóból (vagy másból), akkor szól nektek, hogy a modell azt biztosítsa. Nyilván, utána el kell dönteni, hogy az a modell felelőssége-e, egyébként kibővítheti magának. Vagy egyszerűen megbeszélitek, hogy kinek kisebb ráfordítás megoldani.

**Comment by aaronrancsik** [comment]
Értem, köszönöm!
