### ISSUE TITLE
Radar.setHighlighted implementáció

### ISSUE THREAD

**Issue by zsofiath** [SzFMV2020-Osz/AutomatedCar-B#151]
- setHighlighted(WorldObject): Void függvény implementálása
Highlighted propertit kell beállítani

**Comment by sarilevente** [comment]
A WorldObject amit paraméterként bekérünk, annak a Brush paramétere nem tudjuk kívülről beállítani.
Így evvel a taskkal nem tudunk tovább haladni. (ui.: ha a csapatból van valakinek erre egy megoldási ötlete, az mondja bátran)

**Comment by pintergreg** [comment]
Miért kell az objektumben tárolni a megjelenítési színt? Az nem objektum sajátossága, hanem a megjelenítés magánügye. Bele lehet égetni a XAML-be a színt.

**Comment by zsofiath** [comment]
Nekem úgy rémlik, hogy a highlight miatt megváltozó szín kerülhet bele. @sarilevente én módosítanám a Brush-t hogy legyen public setje.
