### ISSUE TITLE
Message Box for controls

### ISSUE THREAD

**Issue by TravnikGergely** [SzFMV2020-Osz/AutomatedCar-B#158]
Egy gomb lenyomására egy Message box ugrik fel, ami leírja, hogy mely billentyűkkel irányíthatjuk a szimulációt.

-  [x] Message Box
-  [x] Gomb felvétele az input handle-be
-  [x] Gomb lenyomására megnyílik a message box.

**Comment by pintergreg** [comment]
Szerintem ez elkészült.
