### ISSUE TITLE
HP megjelenítés és resetelés

### ISSUE THREAD

**Issue by TravnikGergely** [SzFMV2020-Osz/AutomatedCar-B#159]
**_Done by Team B5_**
_A Hp (health point) az autó élétét jelöli._
- [x]  Az AutomatedCar.cs ben egy Hp property felvétele
- [x]  Gomb bevezetése Hp resetelésre
- [x]  Hp reset -> Wolrd.Instance.ControllerdCar.Hp = (maxvalue)

**Comment by TravnikGergely** [comment]
Ezt az egész Issue-t már megcsinálta valamiért az 5ös csapat, így ezzel nem kell már foglalkoznod.

**Comment by blnttg** [comment]
Uhh erdekes, de rendben, akkor at is rakom Done-ba a taskot.
