### ISSUE TITLE
Team 1 - Sprint 3 - Tolatóradar műszerfala

### ISSUE THREAD

**Issue by TravnikGergely** [SzFMV2020-Osz/AutomatedCar-B#185]
- [ ] Konverterek
- [ ] Téglalapok
- [ ] Distance

_Javaslat:_
![image](https://user-images.githubusercontent.com/61805553/98941224-8c520780-24ec-11eb-9d8d-e29aef68d7ce.png)

**Comment by pintergreg** [comment]
Ez egy elég szép terv!

Annyi megjegyzésem lenne, hogy a dokumentációban egy mockup GUI/wireframe van. Vannak eszökzök amikkel nagyon flancos GUI-kat lehet tervezni mobil apphoz, vagy weblaphoz, pl. [1] [2]. Vannak elég primitívek amik „csak” ilyet tudnak:

![](https://s.plantuml.com/imgw/img-c5e7ec265e074c55da54d48df9944855.webp)

Én egy olyasmi tool-t használok mint a draw.io (a felülete és tudása egész hasonló), tehát nem kifejezetten erre való, így az csak nagyon elnagyolt minta arról, hogy kb. mi az elképzelés.

A múltkor beszéltük, hogy jó lehet egy progressbar is (átszínezve adott szinteknél), valamint a szám egy sima szöveg 7-szegmenses font-tal, de ha ilyen font nem is akad, akkor sincs belőle gond.

[1]: https://moqups.com/templates/wireframes-mockups/
[2]: https://www.mockflow.com/

**Comment by TravnikGergely** [comment]
Ha az szebb lenne vagy jobb akkor megcsináljuk progressbarral, lehet egyszerűbb is lenne.
