### ISSUE TITLE
base WorldObject class implementation

### ISSUE THREAD

**Issue by aaronrancsik** [SzFMV2020-Osz/AutomatedCar-B#19]
Implements WO properties:
- [x] position: int x, int y  point relative to top left
- [x]  fileName string
- [x]  has width, height:
- [x]  zIndex: 0 based
- [x]  polygon: 
- [x]  _rotationCenterPointX:  default 0
- [x]  _rotationCenterPointY:  default 0
- [x] isColidable 
- [x] rotationAngle: default 0
- [x]  highlighted: default false

**Comment by aaronrancsik** [comment]
@lindnermarci  itt, ami még nincs kipipálva azt a WorldObekct konstruktórból be kéne állítani a DoD-ban írt defaultra

**Comment by aaronrancsik** [comment]
zindex alapértelemzettem 0 legyen ne 1

**Comment by lindnermarci** [comment]
Hello, modositottam a zindex, Angle, IsHighlighted beallitasat, A kov propertyket Zsófia allitotta be a megjelenítéstől:
public int _rotationCenterPointX = 90; // = width/2
public int _rotationCenterPointY = 120; // = height/2
