### ISSUE TITLE
B4_Figyelmeztetés kiküldése

### ISSUE THREAD

**Issue by sarilevente** [SzFMV2020-Osz/AutomatedCar-B#195]
Egyeztetés a Dashboard csapattal.
Szeretnénk majd kírni egy figyelmeztető üzenetet egy metódus meghívással. Ez egy string paramétert vár, amiben a Figyelmeztető üzenet szövegét továbbítanánk, ami majd megjelenítésre kerül.

**Comment by pintergreg** [comment]
Van ennek egy dedikált helye a műszerfalon: 
![Képernyőkép_2020-11-18_14-04-01](https://user-images.githubusercontent.com/3854784/99533962-f82de780-29a6-11eb-9c4d-86e3951dbe64.png) 
Talán még konkrét csomag is van rá.
Az az AEB warn doboz felfogható lámpaként és felvillantod sárgán ha baj van, vagy nem tudom.
Nyilván szövege is lehet, de legyen minden állapot megjelenítve.
- sárga/BRAKE -> ha figyelmeztetni kell
- piros/AEB ha a modul vészfékez
- szürke(nem világít)/ AEB text ha nincs semmi gond

Ezek csak példák, nem tudom mi fog kiférni...

**Comment by zsofiath** [comment]
Ehhez egy olyan függvényt kellene írnunk, ami egy void metódust vár paraméterként. Ez a metódus kezelné a jelzést, és tesztelésnél könnyen lehet ellenőrizni hogy meghívódott-e. (a jelzés helyett egy tesztosztály változót állítanánk be, és ezt ellenőriznénk hogy megváltozott-e az értéke.) Így függetlenül a műszerfaltól a saját működésünket le tudjuk tesztelni.
