### ISSUE TITLE
IWorldObject típus biztosítása

### ISSUE THREAD

**Issue by lindnermarci** [SzFMV2020-Osz/AutomatedCar-B#21]
A következő kérdés merült fel meetingünk során:
Az IWorldObject típus példányosítását egy Nuget-ből behúzott IOC keretrendszer kezelje vagy saját magunk biztosítsuk a Singleton objektumot a többi komponens számára?
kontextus: https://app.diagrams.net/#G1Z2PiMbJ_dstfsg5ElBxTfde9KUzypjxt

**Comment by pintergreg** [comment]
@aaronrancsik @lindnermarci Nem tilos új címkéket létrehozni, bár a csapathoz tartozást a *Projects* is biztosítani tudja. Project (tábla) alapján is lehet szűrni az Issues listában (ahogy mérföldkő és címke alapján is).

**Comment by pintergreg** [comment]
> Nuget-ből behúzott IOC keretrendszer 

Nem tudom miről van szó, az IOC rövidítést nem ismerem. Általában véve szabadom lehet csomagokat használni (amíg .NET Core kompatibilis, de ez nem nagyon szokott gond lenni), nem kell újra feltalálni a kereket.

**Comment by aaronrancsik** [comment]
> @aaronrancsik @lindnermarci Nem tilos új címkéket létrehozni, bár a csapathoz tartozást a _Projects_ is biztosítani tudja. Project (tábla) alapján is lehet szűrni az Issues listában (ahogy mérföldkő és címke alapján is).

Igen, végül rájöttünk, hogy project tábla tökéletes lesz arra amire eredetileg a címkét gondoltuk.

**Comment by aaronrancsik** [comment]
> > Nuget-ből behúzott IOC keretrendszer
> 
> Nem tudom miről van szó, az IOC rövidítést nem ismerem. Általában véve szabadom lehet csomagokat használni (amíg .NET Core kompatibilis, de ez nem nagyon szokott gond lenni), nem kell újra feltalálni a kereket.

Igazából prog4 óráról megmaradt, hogy a függőségek feloldását végezheti keretrendszer, Inversion of Control container-t megvalósító Nuget package egy lehetőség, pl. most hirtelen találtam egy ilyet:  [package link](https://www.nuget.org/packages/IoC.Container/)  [github link](https://github.com/DevTeam/IoCContainer) prog4-en valami mást, használtunk, amit most nem találok, illetve nem is biztos hogy .net core kompatibilis. 
De persze jobban belegondolva lehet overkill ez IoC megoldás kb. csak mi vennénk hasznát,  egyszerűbb és mindenkinek jobban érthető lenne, ha csak simán implementálunk egy singletont szálbiztossággal talán nem kell most törődni :D ?  a UI gondolom saját szálon fut, de a komplett business logic egyszálas lesz gondolom. Majd azért körbe nézegetek, de ha jól értem van egy 'fő fő' 'game' osztály amin belül lehet a világot létrehozni és akkor ez a game osztály lesz a létrehozásért felelős.

**Comment by pintergreg** [comment]
@aaronrancsik IOC, nem használtam sosem ilyet. Ha úgy érzed, hogy segít én nem vagyok ellene. Pro-Contra értelemben mi szólhat ellene?

A Game-nek van egy „ütemezője” ami pl. a billentyűzetolvasásnál kell. Ugyanilyenje van a VFB-nek is, emiatt a GameBase osztálynév ami ezt biztosítja a kódban nem is igazán jó. Át kellett volna neveznem TimerBase-nak vagy valami.

A .NET debugger nekem több szálat mutat futtatáskor, de ezeket asszem a „.NET intézi”. Én explicit nem tettem bele több szálasítást és nem is hiszem, hogy kiemelten szükség lenne rá.

**Comment by aaronrancsik** [comment]
Köszi! Ezt az IoC-s dolgok még kicsit átnézem illetve megnézem a singleton minta implementációt is amit küldtél, aztán erre még majd visszatérünk. Az IoC előnye szerintem nagyobb projekteknél lenne igazán, én eddig 'élesben' java spring-el használtam ilyesmit, baromi kényelmes volt, hogy nem kell dependálni egy rakás dologra hanem egy biztosított package felelős a komponensek/modulok létrehozásért. Ebben a projektben nem lesz több olyan (csapat) komponens/modul akik még ezt használnák szerintem, így felesleges komplexitás növelés lenne csak szerintem.

**Comment by aaronrancsik** [comment]
Singleton vagy static lesz végül.
