### ISSUE TITLE
create World without implementation

### ISSUE THREAD

**Issue by aaronrancsik** [SzFMV2020-Osz/AutomatedCar-B#22]
## World
crate empty methods:

- [x] - _automatedCar: AutomatedCar
- [x] - trees: List<WorldObject>
- [x] - signs: List<WorldObject>
- [x] - roads: List<WorldObject>
- [x] - npcs: List<WorldObject>
- [x] + addObject(WorldObject): void
- [x] + NPCs{get; set;} : List<IWordObject>
- [x] + ControlledCar{get; set;} : AutomatedCar
- [x] + getWorldObjectsInTriangle(int a, int b, int c): List<WordObject>
- [x] + getWorldsObjectsInRectangle(int a, int b, int c, int d): List<WordObject>

**Comment by Joshuna** [comment]
Pull request-et nem fogok csinálni. Mert be lett mergelve A B2_Load_world_Objects_be Tomi álltal. Sajnos egy halott ág marad az ága, ami meg lett benne csinálva az bekerül a master-be fent említett branchen keresztül.
