### ISSUE TITLE
Team B4 - Vészfék finomhangolás

### ISSUE THREAD

**Issue by szbotms** [SzFMV2020-Osz/AutomatedCar-B#220]

**Comment by szbotms** [comment]
Az alábbiakat javítottam a branchen:

1. Az AEB eddig tolatás közben is működött, így csak lassan lehetett tolatni, ha volt előtte valami. Egyszerű logika mentén már csak akkor érzékel, ha D-ben van az autó.
2. Az eddigi implementáció flaky volt, mután érzékelt egy közeli objektumot, csak egy pillanatra alkalmazta a féket, mert a következő Run során már nem mindig érzékelte az adott objektumot. Most ha egyszer érzékel, a féket alkalmazza addig, amíg az autó meg nem áll és nem kerül át a váltó N-be, ilyenkor abbamarad a vészfékezés.
3. A UI eddig nem jelzett ki semmit, mert az általunk küldött packetet nem vette figyelembe. Az egyszerűség kevéért a HMI packetet használom a fékezés mértékének megadásához.

**Comment by aaronrancsik** [comment]
> Az alábbiakat javítottam a branchen:
> 
> 1. Az AEB eddig tolatás közben is működött, így csak lassan lehetett tolatni, ha volt előtte valami. Egyszerű logika mentén már csak akkor érzékel, ha D-ben van az autó.
> 2. Az eddigi implementáció flaky volt, mután érzékelt egy közeli objektumot, csak egy pillanatra alkalmazta a féket, mert a következő Run során már nem mindig érzékelte az adott objektumot. Most ha egyszer érzékel, a féket alkalmazza addig, amíg az autó meg nem áll és nem kerül át a váltó N-be, ilyenkor abbamarad a vészfékezés.
> 3. A UI eddig nem jelzett ki semmit, mert az általunk küldött packetet nem vette figyelembe. Az egyszerűség kevéért a HMI packetet használom a fékezés mértékének megadásához.

helló, ráérsz még egy kicsit?
