### ISSUE TITLE
load all world objects via World's static GetInstance() 

### ISSUE THREAD

**Issue by aaronrancsik** [SzFMV2020-Osz/AutomatedCar-B#23]
content of config.txt : https://drive.google.com/file/d/1mbHaztZF1_C7KQz12hlNaQPWt8sy3Pir/view
- currentMapPath
- NPCstaticRoutes
- rotationPoints for 'all' world objects
- polygon description for all world objects
- [x] create static GetInstance() :  World      
- [x] Read config.json
- [ ] Load not movable 'static' world object for the current map
- [ ] Load dynamic objects (AutomatedCar, NPCs)
- [ ] Set NPC's static routes
- [ ] read Polygon descriptions which configured in config.txt

- [x] set fileName filed
- [ ] set width, height: based on image size
- [ ] set zIndex: based on type

**Comment by pintergreg** [comment]
- Mi az config.txt és mit fog tárolni?
- Az NPC 2. sprintes feladat és a B3-é. A modellnek kezelnie kell dinamikus objektumokat (egocar és NPC-k), de az útvonal feltöltés határozottan nem ide tartozik. Leginkább arról van szó, hogy legyen egyértelmű, hogy az objektumhierarchiában hova tartozik majdan egy NPC autó. (Elég neki egy üres osztály most).
- Ezen kívül a DoD pontokhoz képest furának találom a task címét. Arra gondolok, hogy ez a feladat arról szól, hogy legyen a World singleton. Singleton pattern-hez viszont nem érzem követelménynek statikus objektumok betöltését. Tehát kifejezőbb címet kellene találni. Ezt meg lehet támogatni egy leírással is a DoD pontok elé.

Magáról a singleton kialakításról elvileg gondoskodtam a World-ben, bár pongyola módon [benne maradt a kiindulókódban](https://github.com/SzFMV2020-Osz/AutomatedCar-B/blob/master/src/AutomatedCar/Models/World.cs#L8-L9) ez a lazySingleton dolog, amit C#-al kapcsolatban találtam, de nem jártam utána.

**Comment by aaronrancsik** [comment]
> * Mi az config.txt és mit fog tárolni?
> * Az NPC 2. sprintes feladat és a B3-é. A modellnek kezelnie kell dinamikus objektumokat (egocar és NPC-k), de az útvonal feltöltés határozottan nem ide tartozik. Leginkább arról van szó, hogy legyen egyértelmű, hogy az objektumhierarchiában hova tartozik majdan egy NPC autó. (Elég neki egy üres osztály most).
> * Ezen kívül a DoD pontokhoz képest furának találom a task címét. Arra gondolok, hogy ez a feladat arról szól, hogy legyen a World singleton. Singleton pattern-hez viszont nem érzem követelménynek statikus objektumok betöltését. Tehát kifejezőbb címet kellene találni. Ezt meg lehet támogatni egy leírással is a DoD pontok elé.
> 
> Magáról a singleton kialakításról elvileg gondoskodtam a World-ben, bár pongyola módon [benne maradt a kiindulókódban](https://github.com/SzFMV2020-Osz/AutomatedCar-B/blob/master/src/AutomatedCar/Models/World.cs#L8-L9) ez a lazySingleton dolog, amit C#-al kapcsolatban találtam, de nem jártam utána.

Akkor egy csak a singleton szóljon?, mi ilyen 'stréber loading' módon előre felakarjuk tölteni az egész világot létrehozáskor, de ha lazy loading kell akkor megoldjuk úgy.

**Comment by pintergreg** [comment]
> Akkor ez csak a singleton-ról szóljon?, mi ilyen 'stréber loading' módon előre felakarjuk tölteni az egész világot létrehozáskor, de ha lazy loading kell akkor megoldjuk úgy.

Nem, félreérthető voltam. Teljesen jó hogy ha a világ „létrehozáskor” be van népesítve. A kiindulókódban és létrehozok egy üres világot, majd feltöltöm objektumokkal és „elindítom a játékot”.
Szigorúan véve nem a létrehozás részeként (=konstruktorban) népesítem be a világot, hanem a singleton World objektum létrehozása után közvetlenül.
Ennél lazy-bb nem kell. Még a nagyobb világot is el kellene bírnia a CPU-nak.

Talán [ebben](https://csharpindepth.com/articles/Singleton) a cikkben olvastam a LazySingleton dologról, de ez eléggé C#/.NET specifikus. Nem próbáltam ki, nem tudom, hogy mennyivel jobb. Itt jön ki, hogy ez egy nagyon konkrét .NET dolog én meg nem vagyok .NET programozó.

A thread-safe jól jöhet (a kiinduló kód futtatásakor a debugger több szálat is mutat), de egyébként legyen a legegyszerűbb megoldás.

**Comment by pintergreg** [comment]
Én túl merevnek érzem azt a megközelítést, hogy csak a konstruktoron keresztül lehessen objektumokat hozzáadni a világhoz.
Mi lenne ennek az előnye?

**Comment by aaronrancsik** [comment]
Az előnye mindössze annyi lenne, hogy így elvileg különböző állapotok nem fognak létezni, tehát ilyen null jellegű hibákat nem kell kezelnünk, de valóban igencsak merev, szóval a mozgó word object-ek létrehozására akkor adunk lehetőségetm és csak az álló dolgok jönnek létre konstruktor futáskor az így jó lesz nem?

**Comment by pintergreg** [comment]
Én szerintem akkor sem kell null-check-eket végezni ha a WorldObjects gyűjtemény példányosításkor már azonnal létrejön 0 elemmel (ahogy pl. én csináltam a skeletonban). Majd a már létező világ objektumhoz, amiből -révén singleton- kizárólag 1 példány létezhet hozzáadogatjuk a világ többi elemeit.

Abban mindenesetre teljesen igazad van, hogy a statikus objektumok nem fognak a játék futása során bekerülni (valójában a dinamikusan sem feltétlenül). Miután a game.start() meghívásra kerül. Az feltétel, hogy a szoftver kezelje mindkét pályát, de az nem, hogy menet közben cserélhető legyen. Tehát világot felépíteni egyetlen egyszer is elég. Ennek többé kevésbé (nagyjából nézőpont kérdése) a dinamikus objektumok hozzáadása is része.

Nem mondom, hogy hiba van az elképzeléssel. Elvileg működhet a csak konstruktoros verzió is, inkább csak szerettem volna megérteni a gondolatmenetet.

**Comment by tffbs** [comment]
A config.txt-t lecseréltem config.json-re, sokkal flexibilisebb így. A meglévő fileokat már beolvassa és a GetInstance setteli a private WorldObject listákat azok alapján.
