### ISSUE TITLE
getPositionFromScreen metódus létrehozása

### ISSUE THREAD

**Issue by zsofiath** [SzFMV2020-Osz/AutomatedCar-B#26]
A PositionComputeObject-ben kell implementálni a metódust.

Megjelenő területre számított koordináták:
X-EgoCarX+ScreenW/2=Xm
Y-EgoCarY+ScreenH/2=Ym

- [ ] A paraméterként kapott WorldObject koordinátáit számítja át a képernyő bal felső sarkától számított koordinátákra, 

- [ ]  így adja vissza a worldObjectet.

**Comment by kingpeti** [comment]
@zsofiath @sarilevente A számításhoz szükség lenne a játékteret megjelenítő ablak méretére(Width, Height), aminek jelenleg ezen paraméterei bele vannak égetve az XAML-be több helyen is
`src\AutomatedCar\Views\CourseDisplayView.xaml`:
```xml
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             x:Class="AutomatedCar.Views.CourseDisplayView"
             Width="960" Height="720"
             xmlns:models="clr-namespace:AutomatedCar.Models;assembly=AutomatedCar"
             xmlns:local="clr-namespace:AutomatedCar;assembly=AutomatedCar"
             xmlns:visualization="clr-namespace:AutomatedCar.Visualization;assembly=AutomatedCar"
             >

    <UserControl.Styles>
        <Style Selector="ItemsControl#CourseDisplay">
            <Setter Property="Background" Value="#97D1A2"/>
        </Style>
        <Style Selector="ItemsControl#CourseDisplay > ContentPresenter">
            <Setter Property="Canvas.Left" Value="{Binding X, Mode=OneWay}"/>
            <Setter Property="Canvas.Top" Value="{Binding Y, Mode=OneWay}"/>
            <Setter Property="ZIndex" Value="{Binding ZIndex, Mode=OneWay}"/>
        </Style>
    </UserControl.Styles>

    <ScrollViewer Width="960" Height="720" HorizontalAlignment="Left" VerticalAlignment="Top">
        <ItemsControl Name="CourseDisplay"
			DataContext="{Binding World}"
            Items="{Binding WorldObjects, Mode=OneWay}"
            Width="{Binding Width, Mode=OneWay}"
            Height="{Binding Height, Mode=OneWay}"
            HorizontalAlignment="Left" VerticalAlignment="Top"
            >
```
Ebben a kódrészletben a `UserControl`, `ScrollViewer`, és az `ItemsControl` is tartalmaz ilyen információkat. Ezt ki kéne külön paraméterként szervezni, hogy ne legyen duplikáció 😃
Az `ItemsControl` `Width`, `Height` paramétere ugyan ki van szervezve de szerintem az nem a megfelelö `Width`, `Height` a screen számára. Ezért szerintem ehhez kéne egy új issue amiben ezt a kiszervezést megcsináljuk.

**Comment by zsofiath** [comment]
Tegyük a World-be. Akkor a kód így nézne ki:
```c#
<UserControl xmlns="https://github.com/avaloniaui"
             xmlns:x="http://schemas.microsoft.com/winfx/2006/xaml"
             xmlns:d="http://schemas.microsoft.com/expression/blend/2008"
             xmlns:mc="http://schemas.openxmlformats.org/markup-compatibility/2006"
             x:Class="AutomatedCar.Views.CourseDisplayView"
             xmlns:models="clr-namespace:AutomatedCar.Models;assembly=AutomatedCar"
             xmlns:local="clr-namespace:AutomatedCar;assembly=AutomatedCar"
             xmlns:visualization="clr-namespace:AutomatedCar.Visualization;assembly=AutomatedCar"
             DataContext="{Binding World}"
	     Width="{Binding Width, Mode=OneWay}" Height="{Binding Height, Mode=OneWay}"
             >
```
A DataContext majd  egy saját world objektum lesz, mert ebben tudjuk majd tárolni a leszűrt WorldObject listát, amit meg kell jelenítenünk. Ezen a branchen van ennek egy kezdeménye:
https://github.com/SzFMV2020-Osz/AutomatedCar-B/pull/70

Meg ide tehetünk még megjelenítéssel kapcsolatos property-ket is. (pl.: melyik szenzor van bekapcsolva)

**Comment by zsofiath** [comment]
De lehet hogy szebb, ha paraméterként kéri be ezt a két adatot a függvény.

**Comment by kingpeti** [comment]
> De lehet hogy szebb, ha paraméterként kéri be ezt a két adatot a függvény.

Nekem is ez teetszik, hogy paraméterként kapja meg a fügvény a `Width`, `Height` értékeket

**Comment by kingpeti** [comment]
Márcsak az a kérdés hogy a teljes `Word` class-t adjuk át vagy csak ezt a két paramétert? Melyiket preferáljátok? @zsofiath @sarilevente

**Comment by pintergreg** [comment]
A User Control mérete azéer annyi, mert, hogy annak a gui komponens akkorának kell lennie a teljes ablakon belül. A Scroll View mérete azért ugyanez, mert a teljes vezérlőt a ScrollViewnak kell kitöltenie. Azért volt scroll view, hogy egérrel bele tudjak scrollozni, ez jó debug funkció lehet ha nem zavarja a kamerát. Egyébként lehet másfajta panel is.

Az ItemsControl viszont már a skeletonban felveszi a világ méretét elvileg, oda van bindelve a a World.Width és a Wotld.Height.

Azóta ti teljesen máshol tartotok (és bármi át alakítható a feladatmegoldás érdekében), csak azért írom, hogy világos legyen az, hogy a beégetett értékek nem duplikációk, funkciójuk van.
