### ISSUE TITLE
ColorEnum létrehozása

### ISSUE THREAD

**Issue by zsofiath** [SzFMV2020-Osz/AutomatedCar-B#28]
Szenzor színek tárolására szolgáló enum létrehozása.
Elemei:

- [ ] Radar

- [ ] Kamera

- [ ] Ultrahang

**Comment by pintergreg** [comment]
Nem szeretek minden apróságba beleszólni, de azonnal felvetődött a kérdés, hogy miért is kell egy enum, amely a 3 szenzor debug funkciójának színét rögzíti?

Az enum egy elnevezett konstans kb. 
pl. "red" => 1, "green" => 2, "blue" => 3 és akkor a kódban nem 2-van hanem green és mindjárt olvashatóbb (lehet színkód is ott). De az én problémám az egésszel az, hogy tényleg szükséges ez? A legtöbb magas(abb) szintű programozási nyelv rajzolásért felelős keretrendszere alapból tud ilyet. Tehát azt reprodukálni fölösleges.

Én azt mondanám, hogy a szenzor objektumnak van egy olyan tulajdonsága, hogy megjelenítési szín.
Emiatt én a szenzor objektumban tárolnám le a színt, konstansként. 

```c#
class RadarSensor {
    public string Color {get => "red";}
}
```

Apró bökkenő, hogy az 2. sprintes feladat, tehát nem fog most létezni. Mi ennek a feloldása? Mockolás (későbbi előadás témája, de jelen esetben a fönti kód teljesíti is azt a helyettesítő objektumot amiről ez szól).

Ha kicsit továbbgondoljátok felvetődik az a kérdés is, hogy ha nincs ilyen mi lesz kirajzolva...

**Comment by zsofiath** [comment]
Azért szerveztük külön enumba, mert a színezés az inkább megjelenítés szagú, és nem akartuk feleslegesen a szenzorra tolni. Azt terveztük hogy a szenzor poligonokat majd belepasszíroztatjuk az automatedCar-ba. Erre szeretnénk majd egy dummy objektumot létrehozni, ami imitálja, hogy ott vannak, amíg nincsenek benne.
Az ábrába ezek most így szerepelnek:
https://drive.google.com/file/d/1fSxyuqAZj-sq1W9OZR_4cO5s5JKC_kBi/view?usp=sharing
A CourseDisplayViewModel-t kibővítenénk változókkal, amik azt jelzik, hogy melyik szenzor, vagy minden objektum poligonját meg kell jelenítenünk. Azt feltételezzük, hogy a poligonok mindig rendelkezésre állnak. Ha nem majd exception-t dobunk.

A HMI-vel kell majd még egyeztetnünk arról, hogy hogyan tudnák nekünk átadni hogy éppen melyik szenzor látszik. Azt elvileg tőlük kapjuk majd.

**Comment by pintergreg** [comment]
> A CourseDisplayViewModel-t kibővítenénk változókkal, amik azt jelzik, hogy melyik szenzor, vagy minden objektum poligonját meg kell jelenítenünk.

Oké.

> A HMI-vel kell majd még egyeztetnünk arról, hogy hogyan tudnák nekünk átadni hogy éppen melyik szenzor látszik. Azt elvileg tőlük kapjuk majd.

Igen, valami billentyűvel kapcsolhatónak kell lennie. Célszerűen egy buszra írt csomag lesz. DebugOptionsPacket, vagy valami. Ilyen esetben egyébként ti is megtervezhetitek a csomagot és eleve úgy fordultok hozzájuk, hogy egy ilyenre lenne szükség...

**Comment by zsofiath** [comment]
Rendben. Köszi. A buszra írt DebugOptionsPacket tetszik.
