### ISSUE TITLE
CourseDisplayView létrehozás 

### ISSUE THREAD

**Issue by sarilevente** [SzFMV2020-Osz/AutomatedCar-B#29]
A kirajzoló felület lérehozása és elemek felvétele mock-oláshoz.

- [ ] Automated car

- [ ] WorldObjects

**Comment by pintergreg** [comment]
Nem értem ezt az issue-t. Lehet, hogy egy másik megmagyarázza, de akkor azt be kell hivatkozni. Egyébként pedig a kiinduló kód ezt így készen biztosítja.
