### ISSUE TITLE
Dumy szenzorok létrehozása az AutomatedCar objektumban

### ISSUE THREAD

**Issue by zsofiath** [SzFMV2020-Osz/AutomatedCar-B#32]
~~Kell egy AutomatedCar-t öröklő dummy objektum, ami tartalmazza a~~
Az automatedCar-ba kell beletenni a 

- [ ] getCamera(): Polygon

- [ ] getUltra(): Polygon

- [ ] getRadar(): Polygon

metódusokat, amik beégetett poligont adnak vissza (3 szöget), hogy legyen mit kirajzolnunk.

Készüljön egy ilyen interface : IVisibleSensors. Ezt implementálja majd az AutomatedCar.

**Comment by pintergreg** [comment]
Nem vagyok meggyőződve, hogy erre szükség van. A másik issue-ban volt szó arról, hogy a szenzort mock-olod, de nem egyszerűbb a valódi autóba beletenni egy mock-szenzort mint csinálni egy mock-autót benne mock-szenzorokkal?

**Comment by zsofiath** [comment]
De, igazad van. Átírom az issue-t hogy ne felejtődjön el.
