### ISSUE TITLE
Implement SetScaling function

### ISSUE THREAD

**Issue by kingpeti** [SzFMV2020-Osz/AutomatedCar-B#35]
[Modulok diagram](https://drive.google.com/file/d/1fSxyuqAZj-sq1W9OZR_4cO5s5JKC_kBi/view)
Kép méretezése a WordObjects paraméterei alapján.

A WorldObjectTransformer-en belül kell létrehozni.

**Comment by zsofiath** [comment]
Elkezdtem kísérletezni, hogy mit tudok módosítani a meglévő kódon. Van egy Scaler konverter. azt be tudtam üzemelni az autón (tudom, hogy nem itt lesz használva végül).
A CourseDisplayView.xaml-ben ezt írtam át:
`                        <Image Width="{Binding Width, Converter={x:Static visualization:Scaler.Instance}}"
							   Height="{Binding Height, Converter={x:Static visualization:Scaler.Instance}}"
                            Source="{Binding Filename, Converter={x:Static visualization:WorldObjectTransformer.Instance}}"/>`

Valószínűleg nem függvényt kell létrehoznunk, hanem a **Scaler** konvertert kibővítenünk úgy hogy meg tudja csinálni a méretezést.

**Comment by pintergreg** [comment]
> Valószínűleg nem függvényt kell létrehoznunk, hanem a **Scaler** konvertert kibővítenünk úgy hogy meg tudja csinálni a méretezést.

Pontosan erről van szó. A forgatáshoz is hasonló elvet képzeltem el.
