### ISSUE TITLE
Kamera Polygon megjelenítése

### ISSUE THREAD

**Issue by sarilevente** [SzFMV2020-Osz/AutomatedCar-B#37]
~~Biztosítunk egy interface-t a többi modulnak, ahol ha beküldik az saját radar,kamera,ultrahang poligonjaikat, s mi kirajzoljuk azt.~~

#63 alapján Kamera megjelenítése zöld színnel.

**Comment by zsofiath** [comment]
Ez lehetne maga az automatedCar ami implementálja. Azt kiegészíthetnénk ezekkel a tolajdonságokkal, és akkor ezen az objektumon keresztül kapnánk meg ezeket is.

**Comment by sarilevente** [comment]
https://github.com/SzFMV2020-Osz/AutomatedCar-B/pull/80

itt a link ennek a megoldásához
