### ISSUE TITLE
Implement Motor class

### ISSUE THREAD

**Issue by ddfdfg** [SzFMV2020-Osz/AutomatedCar-B#38]
DoD:

- [ ] Motor osztaly letrehozasa, rpm propertyvel

**Comment by pintergreg** [comment]
Mi egyebet csinál még ez az osztály, azon túl, hogy van egy rpm property-je?

***

A DoD-t lehjobb task listel csinálni:

```markdown
- [ ] foo
- [x] bar
```

Beleszerkesztettem az issue leírásba is.

**Comment by ddfdfg** [comment]
nem, igy valoban nem volt ertelme kulon osztalykent kiszervezni - az EngineController classon belul lesz megvalositva, ezt az issues lezarom
