### ISSUE TITLE
Egyeztetes a tobbi csapattal VirtualFunctionBus-szal valo kommunikacio kapcsan

### ISSUE THREAD

**Issue by ddfdfg** [SzFMV2020-Osz/AutomatedCar-B#40]
DoD:

- [x] Kideriteni, melyik csapat kesziti a VirtualFunctionBust

- [ ] Leegyeztetni veluk a PowerTrainPackage osztaly implementalasat

- [ ] Leegyeztetni veluk a getPowerTrainPackage fuggveny implementalasat

- [ ] Leegyeztetni veluk a tolunk kimeno adatok formatumat

**Comment by pintergreg** [comment]
> Kideriteni, melyik csapat kesziti a VirtualFunctionBust

Én. Már benne van a repóban, készen, egy bugyuta példa rá is van kötve, hogy a működését is meg lehessen vizsgálni egy debuggerrel (meg a jegyzetben le is írtam).

**Comment by ddfdfg** [comment]
Felreertes/felkeszuletlenseg miatt lett megnyitva, igy targytalan a kerdes (legalabbis ilyen formaban)
