### ISSUE TITLE
SteeringWheelController Class

### ISSUE THREAD

**Issue by ddfdfg** [SzFMV2020-Osz/AutomatedCar-B#41]
DoD:

- [ ] CalculateRotation() fuggveny implementalasa (auto elfordulasanak szamitasa kormany elfordulasbol)

- [ ] SteeringWheelController Class létrehozása

**Comment by pintergreg** [comment]
Az issue szövegezése alapján nem ismert, hogy:

- kormány elfordulás milyen érték, milyen típus, milyen limitekkel
- az autó elfordulás milyen érték, milyen típus, milyen limitekkel, mihez viszonyítva

Nyugodtan lehet még DoD pont, hogy az osztályt létrehozod pl. Egyébként meg más funkciója nincs mit egyetlen metódust tartalmazni?
