### ISSUE TITLE
Rotation matrix helyett forgatás szög?

### ISSUE THREAD

**Issue by aaronrancsik** [SzFMV2020-Osz/AutomatedCar-B#54]
Az lenne a kérdésem, hogy van bármi haszna annak hogy a világ objectben rotációs mátrixként tároljuk a forgatást?
Értem hogy a fájlokban így van tárolva, de nem lenne jobb ha beolvasáskor egyből átalakítanánk egy 0-360 fokos double skálára?
Ha jól látom a megjelenítés is azzal fog dolgozni,
Van bármi ami arra épül, hogy ez itt mátrixban legyen eltárolva?

**Comment by pintergreg** [comment]
De. Ez egy teljesen jogos felvetés, szerintem sokkal hasznosabb lenne fokban és úgy gondolom, hogy a @SzFMV2020-Osz/team-b4 is értékelné.

**Comment by aaronrancsik** [comment]
@SzFMV2020-Osz/team-b2  @zsofiath Akkor nektek is jó ugye ha alapból forgatási szöget tárolunk a WordObject-ekben transzformációs mátrix helyett egy double 0-360 -as skálán?

**Comment by zsofiath** [comment]
Igen, tökéletes. Az avaloniás tapasztalatok alapján is szimpatikusabb így. Köszi.
