### ISSUE TITLE
Szükséges a minta Car osztály?

### ISSUE THREAD

**Issue by aaronrancsik** [SzFMV2020-Osz/AutomatedCar-B#55]
Van bármi a későbbikben  ami  indokolttá teszi ennek az osztálynak a létezését?  vagy nyugodtan törölhetjük?

**Comment by pintergreg** [comment]
Nekem az volt az elképzelésem, hogy a vezérelt és az NPC autó esetleg közös őstől származik, mert hát mind a kettő autó. De semmi sem kötelez, arra, hogy ez így legyen megoldva. Kitörölhetitek.

**Comment by aaronrancsik** [comment]
Én nem látok semmi olyan adatot ami közös lenne a kettő között, tehát most kitöröljük, de ha lesz közös adat akkor majd átgondoljuk a struktúrát.
