### ISSUE TITLE
Github push noti [META]

### ISSUE THREAD

**Issue by aaronrancsik** [SzFMV2020-Osz/AutomatedCar-B#56]
Tudom nem teljesen ide tartozik.. sorry @pintergreg 
Van valami egyszerű módja annak, hogy azokról az értesítésekről amik megjelennek a github jobb felső sarkában a harang ikonnál, azokról rendszer szinten kapjak értesítést linuxon?
Tudom van mobil github app az sajnos nekem nem opció.
Tudom e-mail-t is küld ha beállítom és akkor az e-mail notit megkapom, de ha lenne egyszerűbb módja pl egy systemd szervíz  ami rendes dbus notification-öket generálna az nagyok király lenne.
Lehet rosszul közelítem meg és valami baromi egyszerű megoldás van rá. 
Én eddig csak ilyen repó függő bonyolult konfig mágia megoldásokat találtam.
Az is jó ha a böngésző küld push notit, de ezt se tudtam beállítani csak frissítésre frissül, vagy max az oldalon belül értesít, de azt meg nem látom ha nem épp ezt az oldalt nézem.
Köszi.

**Comment by pintergreg** [comment]
Nem tudok erre konyhakész megoldást.

Egy gyors keresést követően 3 dolgot találtam:

1. https://github.com/jhass/github_desktop_notifications
    - elég halottnak tűnik, ráadásul még nem is nagyon hallottam erről a nyelvről
2. https://github.com/octobox/octobox#desktop-usage
    - ez egy sokkal komplexebb dolog, nem töltöttem időt annak megértésével, hogy pontosan mire is való, a readme-be beleolvasva van valamiféle desktop módja
3. https://github.com/GABAnich/github-linux-notification
    - Ez valójában egy személyes projekt 2 szkriptből, de azt mondanám, hogy messze a legígéretesebb.
    - Tulajdonképpen semmi egyebet nem csinál mint egy személyes token segítségével (settings-ben tudsz ilyet generálni) lekéri az értesítéseidet, feldolgozza a JSON választ és kiküldi a libnotify-nak. Majd ha jól látom egy ciklusban futtatja az egészet.
    - Én valójában az a bash script részt is Pythonban írnám meg, de ha ismersz bármilyen szkriptnyelvet (Python, Ruby stb) akkor ez alapján összerakhatod magadnak (akár kifinomultabban is).

**Comment by aaronrancsik** [comment]
Köszi szépen, megnézegetem.
