### ISSUE TITLE
VALAHOGY megoldani, hogy  a WorldObjektekhez tartozó poligon megjelenítése ki-be kapcsolható legyen

### ISSUE THREAD

**Issue by zsofiath** [SzFMV2020-Osz/AutomatedCar-B#57]
Egy lehetséges megoldás...

Minta:
```c#
<DataTemplate DataType="{x:Type models:AutomatedCar}">
	<Canvas  Width="{Binding Width}" Height="{Binding Height}" >
		<Canvas.RenderTransform>
			<TransformGroup>
				<RotateTransform  Angle="{Binding Angle}" />
				<TranslateTransform  X="{Binding RotationCenterPointX}" />
				<TranslateTransform  Y="{Binding RotationCenterPointY}" />
			</TransformGroup>
			
		</Canvas.RenderTransform>
		<Image
			Source="{Binding Filename, Converter={x:Static visualization:WorldObjectTransformer.Instance}}"/>
		<Polyline IsVisible="{Binding PoligonVisible}" Stroke="{Binding Brush, Mode=OneWay}"
					Points="{Binding Geometry.Points, Mode=OneWay}" />
	</Canvas>
</DataTemplate>
```

A WordObjekthez kell felvenni PoligonVisible:bool tulajdonságot. Az elemeken végig iterálva majd beállítjuk a buszról szedett adatok alapján. Ha debug módban vagyuk, akkor true, egyébként false. Az xml-be a IsVisible="{Binding PoligonVisible}"-t kel felvenni.

**Comment by zsofiath** [comment]
@pintergreg , neked nincs ötleted, hogy az Polyline tagen belül hogy tudnék bindolni a viewmodelben szereplő változóhoz? Ott tárolnánk hogy a debug mode be van-e kapcsolva, vagy sem. Nem annyira tetszik hogy ezt is a WorldObject-be passzírozzam, de nem találtam meg hogy kellene másképp.
Órán elhangzott a Style tag használata, de oda nem tudom hogy kell leírni az IsVisible-t, és az a probléma is ott van, hogy a viewModel-be felvett tagokat nem érem el, csak a WorldObjectet, amihez a style tartozik.

**Comment by pintergreg** [comment]
> Órán elhangzott a Style tag használata, de oda nem tudom hogy kell leírni az IsVisible-t, és az a probléma is ott van, hogy a viewModel-be felvett tagokat nem érem el, csak a WorldObjectet, amihez a sty

```xml
<Polyline Stroke="{Binding Brush, Mode=OneWay}"
                Classes="Polygon" IsVisible="{Binding Visible}"
		Points="{Binding Geometry.Points, Mode=OneWay}" />
```

A `Binding_IsVisible` branchre feltettem a teljes példát (space billentyűvel kapcsolgatom, csak nincs lekezelve, hogy egy leütés egy kapcsolás legyen ezért lehet, hogy többször oda-vissza váltogatja és a végén látszatra ugyanabban az állapotban marad.)

**Comment by pintergreg** [comment]
Továbbá én az egész UserControl-t a World-re bindeltem, vagyis a CourseDisplayViewModel-ből mást nem érhetsz el.
Azt lehet, hogy a UC DataContext sorát kiveszed (ekkor alapból a hozzá tartozó ViewModelre bindelődik és csak a ScrollViewer-t bindeled a Worldre.

De ez még nem elég, még mindig ki kell nyúlni a Worldből, erre jó elvileg a [$parent`](https://avaloniaui.net/docs/binding/binding-to-controls#binding-to-an-ancestor). Ezt mondjuk még nem sikerült erre a példára megcsinálnom.

**Comment by pintergreg** [comment]
Workaround ha a debug opció a Worldben van eltárolva, kényelmesen elérhető, de sokkal jobb mintha a WorldObjectben lenne.

Így el lehet érni az ItemsControlt amit a fenti alapján a Worldre bindelhetsz.
```xml
<Polyline Stroke="{Binding Brush, Mode=OneWay}" IsVisible="{Binding $parent[ItemsControl].DataContext.DebugW}" Points="{Binding Geometry.Points, Mode=OneWay}" />
```

Még ebből kéne valahogy az ItemsControl-tól följebb menni a UserControlig és akkor tökéletes.

**Comment by zsofiath** [comment]
Felpusholtam, amit sikerült összehoznom, de a isVisible telibe pottyantja hogy ott virít az a false a world-ben. Nem tudom mit nézhettem be rajta :S

**Comment by pintergreg** [comment]
Az Avalonia csak property-ket olvas.

Kipróbáltam így:

```csharp
        private bool debugOn = false;
        public bool DebugOn { get => this.debugOn; }
```

És nem rajzolja ki a poligont.

**Comment by zsofiath** [comment]
Köszönöm.
