### ISSUE TITLE
implement ReadPolygons

### ISSUE THREAD

**Issue by aaronrancsik** [SzFMV2020-Osz/AutomatedCar-B#60]
Function in World whit this signature:

- [x] static ReadPolygons(string filename) :  List<WorldObject>

Logic: 
- [x] param JSON file path deserialization from assets

- [x] Returns WorldObject List in order to match filenames

**Comment by tffbs** [comment]
Huge refactor: a single WorldObject could have multiple polygons that are not connected.
Changed WorldObject.Polygon to WorldObject.Polygon[]
