### ISSUE TITLE
Create Avalonai.Polygon and NetTopologySuite.Geometry

### ISSUE THREAD

**Issue by aaronrancsik** [SzFMV2020-Osz/AutomatedCar-B#62]
- [ ] static method in WordObject

- [ ] called from getInstance

- [x] NetTopologySuite basic knowledge needed

- [x] Create Avalonia polygo from raw pints data

- [x] NetTopologySuite.Geometry from raw pints data

- [ ] use two helper function for the sake of clear code

**Comment by pintergreg** [comment]
Véleményem szerint a JSON-ből egyszerűbb megcsinálni a NTS Geometriákat mint Avalonia poligonból. 

Ezzen az az oka, hogy amint [a fórumba csatolt](https://github.com/orgs/SzFMV2020-Osz/teams/everyone/discussions/5) mintakódomban is látszik, NTS poligont csak LinearRingből lehet csinálni, az meg koordinátapárokat vár Coordinate példányokban. A JSON meg egy listányi koordináta párokat tárol tömbökben, azt végigjárva ezt simán meg lehet csinálni.

Egyébként meg „szét kellene bontani” (ki kell belőle nyerni a pontokat) az Avalonia Poligont és erre nem tudom van-e metódusa.

Egyébként mégis a mégis az 1-es opció lett kiválasztva?

**Comment by aaronrancsik** [comment]
> Véleményem szerint a JSON-ből egyszerűbb megcsinálni a NTS Geometriákat mint Avalonia poligonból.
>
> Ezzen az az oka, hogy amint [a fórumba csatolt](https://github.com/orgs/SzFMV2020-Osz/teams/everyone/discussions/5) mintakódomban is látszik, NTS poligont csak LinearRingből lehet csinálni, az meg koordinátapárokat vár Coordinate példányokban. A JSON meg egy listányi koordináta párokat tárol tömbökben, azt végigjárva ezt simán meg lehet csinálni.

Cseréljük.

> Egyébként meg „szét kellene bontani” (ki kell belőle nyerni a pontokat) az Avalonia Poligont és erre nem tudom van-e metódusa.

Igen, erre van metódus

> Egyébként mégis a mégis az 1-es opció lett kiválasztva?

Valóban félreérthető, ez a 2. opció lenne csak egyszerre feltöltést segíti ez a függvény.

**Comment by pintergreg** [comment]
> Igen, erre van metódus

Akkor nekem így is jó. Ha egyszerűbbnek találjátok, akkor legyen.

**Comment by aaronrancsik** [comment]
note: szétbontjuk 2 függvényre

**Comment by aaronrancsik** [comment]
Megvalósul a jelenlegi megoldással.
