### ISSUE TITLE
(ItemsControl felvétele a szenzoroknak helyett) Radar szenzor megjelenítése

### ISSUE THREAD

**Issue by zsofiath** [SzFMV2020-Osz/AutomatedCar-B#63]
~~Valami ilyesmit kell felvenni a WorldObjects ItemControljával egy szinten:~~
~~<ItemsControl Items="{Binding <Szenzorok>, Mode=OneWay}~~

~~és ebbe belerajzolni 3szögeket, hogy kiderüljön, hogyan kell a szenzornak kinéznie.~~

- [x] PlayerCar objektum felvétele, hogy elkülönüljön a többi WorldObject-től (WorldObject-ből öröklődik)

- [x] Radar változók felvétele a PlayerCar-ban

(ha szenzoron belülre tettem, nem kajálta az avalonia)
```c#
public SolidColorBrush RadarBrush { get; set; }
public Geometry RadarGeometry { get; set; }
public bool RadarVisible{ get; set; }
```

- [x] DataTemplate felvétele a PlayerCar-nak !!! a WorldObject-ek DataTemplate-je elé, mert ezek úgy működnek mint a switch-case, és a PlayerCar is egy WorldObject !!!

- [x] Polyline felvétele a Radarnak a keretet megjelenítő polyline alá.

**Comment by zsofiath** [comment]
ItemsControl-ból nem lehet kettőt felvenni egy ScrollViewer-en belül.

**Comment by pintergreg** [comment]
> ItemsControl-ból nem lehet kettőt felvenni egy ScrollViewer-en belül.

Ettől tartottam én is.

**Comment by zsofiath** [comment]
Sőt. UserControl-on belül sem enged még egy ScrollViewer-t felvenni. Nem nagyon van más ötletem hogy lehetne ebbe a UserControlba bármi mást beletenni a WorldObjekten kívül.

**Comment by zsofiath** [comment]
Megvan a megoldás. (Nem szép, de így működik.) Beírtam a leírásba.

**Comment by zsofiath** [comment]
@sarilevente , @kingpeti  Ennek mintájára lehetne megcsinálni a Kamera, és Ultrahang szenzorokat is.
