### ISSUE TITLE
Látszó elemek lekérdezése a World-től

### ISSUE THREAD

**Issue by zsofiath** [SzFMV2020-Osz/AutomatedCar-B#66]
A World.getWorldsObjectsInRectangle(int a, int b, int c, int d): List<WordObject> segítségével kell kiszedni az éppen megjelenő elemeket. Ehhez a PositionComputeObject getScreenSquare metódusát kell használni.

Le kell cserélni a World kontextust valami sajátra, ami tartalmazza:
PlayerCar-t
Leszürt WorldObjecteket

A kapott elemeket kell az ItemsControl Items mezőjében megadni.

**Comment by zsofiath** [comment]
Vagy Lehet inkább getWorldsObjectsInRectangle-t meghíva, nem az elemeket kellene visszakapnunk, hanem a World-be létrehozni egy VisibleObjects válzótozót, amit feltöltene elemekkel. Akkor maradhat a World a kontextus. @aaronrancsik , ezt tudnátok így csinálni?

**Comment by aaronrancsik** [comment]
> Le kell cserélni a World kontextust valami sajátra, ami tartalmazza:
> PlayerCar-t
> Leszürt WorldObjecteket

Ezt nem értem.

> Vagy Lehet inkább getWorldsObjectsInRectangle-t meghíva, nem az elemeket kellene visszakapnunk, hanem a World-be létrehozni egy VisibleObjects válzótozót, amit feltöltene elemekkel. Akkor maradhat a World a kontextus. @aaronrancsik , ezt tudnátok így csinálni?

Szerintem nem lenne szép architektúra szempontjából ha a világ tudna a VisibeObject típus létezéséről, viszont egy adapter függvényt osztály csinálhatunk ami WorldObject listából VisibleObejct listát csinál. De mivel igazából ti hozzátok létre a VisibleObject-et akár a VisibleObject-nek is lehetnek egy olyan metódusa hogy createFromWorldObject(WorldObject obj):VisibleObject

**Comment by zsofiath** [comment]
> Ezt nem értem.

Ez avaloniás fogalom. Nincs dolgotok vele. Ez az az objektum aminek az elemei láthatóak a xaml fájlban. Meg kell adni a tag-en belül.

Közben azt hiszem, rájöttem a megoldásra. Létrehozok egy  VisualizationWorld objektet, és abba pakolok mindent ami a vizualizációnak kell.  Ez tárolná a látszó worldobject-ek referenciáját. A valódi World mellett jönne létre az App.xaml.cs-ben. Ez lesz a Context amit használunk a xaml-ben.

**Comment by zsofiath** [comment]
World.getWorldsObjectsInRectangle(int a, int b, int c, int d)

(P1.x = P2.x = a)
