### ISSUE TITLE
PlayerCar középpen tartása, többi elem mozgatása

### ISSUE THREAD

**Issue by zsofiath** [SzFMV2020-Osz/AutomatedCar-B#67]
A positionComputeObject segítségével kell középre pozícionálni a PlayerCart. Nyilak mozgatására a többi objektumnak kell elmozdulnia.

- [x] PlayerCar középpen jelenjen meg, de ne írjuk felül az X,Y koordinátákat, mert azt a többi modul használja.

- [x] Néhány Dummy objektum elhelyezése a terepen

- [x] positionComputeObject metódusainak segítségével az elemek pozícionálása amikor elmozgatjuk az autót

**Comment by zsofiath** [comment]
@pintergreg elakadtam ezzel a taskkal.
Első körben a 0,0 helyre akartam mozgatni az autót, és mivel rajta van a <TranslateTransform  X="{Binding RotationCenterPointX}" />, ezért hogy az eredeti helyén legyen ennyit kellene visszafelé mozgatnom, úgy hogy nem írom felül az X-t. Erre a convertert találtam alkalmas megoldásnak, mert az nem módosítja az eredeti objektumot, csak hát a style tagen belül nem működött.

Kivettem az adott Style sorokat, és áttettem a canvasba a Left-et meg a Top-ot, de így viszont nem mozog az autó gombnyomásra.
Terveztem valahova egy loopot tenni, ami a frissítésért lenne felelős, de nem tudom hol van ez a rész akódban, amit újra meg újra futtatnom kéne a folyamatos kirajzolásért.

**Comment by pintergreg** [comment]
Az elv jónak tűnik. Kipróbáltam és látom, amit írsz, de hova próbáltad lehozni a converteres részt?

**Comment by zsofiath** [comment]
Fönt van a Setterben, csak kikommenteztem, hogy a lenti X-Y bindingot megnézzem.
```c#
<Setter Property="Canvas.Left" Value="{Binding X, Mode=OneWay, Converter={x:Static visualization:TranslateSetback.Instance}}"/>
```
Mivel nem mozgott az autó a convertertől függetlenül, ezért ide már nem tettem be.

**Comment by zsofiath** [comment]
Az lehet esetleg megoldás, hogy felveszünk a worldObject-nek egy VisibleX, és VisibleY propertit, amit a vizualizáció állít be, és ez alapján rajzolódik a képernyőre, és nem erőltetjük a converter használatát.

**Comment by pintergreg** [comment]
De a vizualizáció hol állítaná be? Az általam elképzelt architektúra szerint a megjelenítés nem írja a modellt. 
Nyilván nem egy szép megoldás és ezt gondolom te is érzed, de konkrétan nagyobb baj, hogy én nem is látom, hogy hol lehetne ezt megcsinálni.

Játszottam én is a converter-rel tegnap, de nem jutottam megoldásra.

**Comment by zsofiath** [comment]
A Game.cs-ben van a Tick függvény. Annak az alján kellene meghívni egy abstract függvényt:

ScreenPositioner. AlignItemsToScreen(world)

Ebben szépen feltöltenénk a visualization<X/Y> propertiket.
Ez még csak ötlet, de megnézem, működik-e.

**Comment by zsofiath** [comment]
Az ötlet működni látszik. Így középen van, és a fekete kör mozog hozzá képest.

**Comment by zsofiath** [comment]
Tettem bele néhány tesztet is, de nem túl segítőkész, ha elrontok valamit.
Ennyit ír csak hibaüzenetnek:
![image](https://user-images.githubusercontent.com/17666549/95318946-876bb980-0897-11eb-8b2b-261032b2bb29.png)

Részletesebb logot hol tudok megnézni @pintergreg?
