### ISSUE TITLE
Highlighted WorldObject property

### ISSUE THREAD

**Issue by zsofiath** [SzFMV2020-Osz/AutomatedCar-B#69]
Fel kell venni egy új PolyLine-t a WorldObjektekhez a xaml fájlban, ami az IsHighlighted-re bindolódik.
Ez szolgál  majd az ütközés esetén megjelenő keretként.
(Esetleg adhatunk neki vastagabb stroke-t)

**Comment by aaronrancsik** [comment]
Amint bekerül a master-re ez a PR https://github.com/SzFMV2020-Osz/AutomatedCar-B/pull/53 akkor már lesz ilyen tulajdonsága a WorldObject-nek

**Comment by zsofiath** [comment]
Bocsi, a xaml-re gondoltam. Javítottam a leírást.

**Comment by zsofiath** [comment]
https://github.com/orgs/SzFMV2020-Osz/teams/group-b/discussions/3

> Ez akkor történik, amikor majd a 2. sprintben létrehozandó szenzor látómezejébe kerül pl. egy fa, akkor a szenzor a fa highlighted tulajdonságát bebillenti és ekkor a megjelenítésnek valami más színt kell tudnia használni (a poligon kirajzolására, esetleg kiszínezésére: Fill tulajdonság). Én a magyarázó rajzokon sárgát szoktam használni.

> Ez csak debug módban él, és az is jó, ha a debug poligon pl. lila, és amikor a szenzor megjelöli akkor nem lila, hanem sárga, vagy sárgáza színezett, vagy mindegy. Ehhez a színezéshez nem kell színt tárolni a modellben. Ez a kijelölő szín, akár a XAML-be is lehet égetve.

**Comment by zsofiath** [comment]
@kingpeti van kedved elvinni ezt a taskot?

**Comment by kingpeti** [comment]
@SzFMV2020-Osz/team-b2 Ahoz hogy ezt a taskot meg tudjuk csinálni ahoz kell hogy minden IsHighlighted tulajdonsággal rendelkezö azaz minden WordObject leszarmazotnak sajat Geometryje, mert Point-okra bindoljuk a Highlighted teruletet.
Jelenleg csak az AutomatedCar tartalmaz ilyet ott meg is jelenik jól, de a többin nem, mert azoknak nincs.
Kiprobáltam egy pedestrian-el is és [müködik a Highlight](https://teams.microsoft.com/l/message/19:e17923f8738f4a9ab11bc1431a2f9116@thread.tacv2/1602080861466?tenantId=1d6a56fa-705a-4bbc-8004-67a21d5e9b97&groupId=a56552c3-1b48-44d8-af21-7ac594aa9009&parentMessageId=1602080861466&teamName=SzFVM%202020%20%C5%91sz&channelName=B4%20TEAM&createdTime=1602080861466).
