### ISSUE TITLE
A master branch-re sikeresen kikerült egy olyan merge ami miatt jelenleg futásidőben elszáll...

### ISSUE THREAD

**Issue by aaronrancsik** [SzFMV2020-Osz/AutomatedCar-B#87]
Ha jól látom B3-ból jön a merge.
Jó lenne ezt minél hamarabb fixálni mert nehezíti a munkánkat.

**Comment by aaronrancsik** [comment]
@SzFMV2020-Osz/team-b3 
Ha jól látom ez tőletek jön.

**Comment by aaronrancsik** [comment]
@pintergreg Ilyen esetben mi a teendő?

**Comment by ddfdfg** [comment]
Attekinthetoseg miatt ide is beirom: igen, bocsi, eszleltem en is delutan, erre nyitottam ezt a PRt:
https://github.com/SzFMV2020-Osz/AutomatedCar-B/pull/84
Remelhetoleg mielobb bemegy, de addig is, localon 1 sor kommentelesevel/torlesevel ideiglenesen megoldhato. AutomatedCard.cs osztalyban, a konstruktorabol ha torlod/kommenteled a PowerTraint, akkor nem dobalja a hiba (ez fog bemenni a linkelt PRben is). Meg egyszer bocsi, de azert ezzel a megoldassal remelem tud mindenki haladni addig is
