### ISSUE TITLE
Add missing IsHighlighted propery to WordObject descendants

### ISSUE THREAD

**Issue by kingpeti** [SzFMV2020-Osz/AutomatedCar-B#94]
@SzFMV2020-Osz/team-b2 Ahhoz hogy a #69 tudjon müködni ahhoz az kell hogy minden IsHighlighted tulajdonsággal rendelkező Modell azaz minden WordObject leszarmazotaknak saját Geometryje legyen, mert Points-okra bindoljuk a Highlighted területet.
Jelenleg csak az AutomatedCar tartalmaz ilyet ott meg is jelenik jól, de a többin nem, mert azoknak nincs.
Kipróbáltam egy pedestrian-el is és [működik a Highlight](https://teams.microsoft.com/l/message/19:e17923f8738f4a9ab11bc1431a2f9116@thread.tacv2/1602080861466?tenantId=1d6a56fa-705a-4bbc-8004-67a21d5e9b97&groupId=a56552c3-1b48-44d8-af21-7ac594aa9009&parentMessageId=1602080861466&teamName=SzFVM%202020%20%C5%91sz&channelName=B4%20TEAM&createdTime=1602080861466).

**Comment by aaronrancsik** [comment]
@kingpeti Ez már nem releváns ugye? ha mégis, nyisd újra.
