### ISSUE TITLE
B4: Worldobject-ek megfelelo meretezese

### ISSUE THREAD

**Issue by szbotms** [SzFMV2020-Osz/AutomatedCar-B#98]

**Comment by aaronrancsik** [comment]
Egy kicsit tudsz specifikusabb lenni? arra gondolsz, hogy a wo-hoz tartozó kép jó mérettel jelenjen meg?, mert ez már megtörténik itt  #97 , csak a forgatás még nem

**Comment by zsofiath** [comment]
@szbotms ezt a taskot lezárom. Most úgy néz ki még  sincs ilyenre szükség, mert jól jelennek meg a dolgok.
